name: Sample Jenkins Action
on:
  workflow_dispatch:
jobs:
  build:    
    runs-on: self-hosted  
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v2

      - id: sampleaction
        uses: Abhilash-1201/NodeJsBoilerplateCode@master
        with:
          jenkins-server:  "${{ secrets.JENKINS_SERVER }}" # URL of the jenkins server
          jenkins-job: "nodejscode1201" # The name of the jenkins job to run
          jenkins-username: ${{ secrets.JENKINS_USERNAME }} # user name for accessing jenkins
          jenkins-pat: ${{ secrets.JENKINS_PAT }} # personal Access token for accessing Jenkins
          poll-time: 10 # how often to poll the jenkins server for results
          timeout-value: 600 # How long to poll before timing out the action
          verbose: true # true/false - turns on extra logging
          
      - name: Use git-auto-commit-action
        id: "auto-commit-action"
        uses: ./

      - name: "no changes detected"
        if: steps.auto-commit-action.outputs.changes_detected == false
        run: "echo \"No changes detected\""

      - name: "changes detected"
        if: steps.auto-commit-action.outputs.changes_detected == true
        run: "echo \"Changes detected\""
